/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "on-tertiary-fixed": "#4a2642",
              "on-error": "#fff7f7",
              "inverse-on-surface": "#a09ba1",
              "tertiary-fixed": "#f4bfe3",
              "on-secondary-fixed-variant": "#5f586e",
              "secondary-dim": "#565065",
              "on-primary": "#fdf7ff",
              "outline": "#7d7983",
              "secondary-container": "#e8def8",
              "primary-fixed": "#d4c3fd",
              "tertiary-dim": "#6e4664",
              "surface-container-lowest": "#ffffff",
              "on-surface": "#34313a",
              "primary-fixed-dim": "#c6b6ee",
              "on-surface-variant": "#615d68",
              "background": "#fdf7fe",
              "on-background": "#34313a",
              "on-secondary-container": "#554f63",
              "tertiary": "#7b5270",
              "on-secondary-fixed": "#423c50",
              "error-container": "#f97386",
              "primary-container": "#d4c3fd",
              "secondary-fixed-dim": "#dad0ea",
              "surface": "#fdf7fe",
              "on-primary-fixed-variant": "#524576",
              "surface-container-highest": "#e7e0ec",
              "surface-container": "#f2ecf5",
              "on-secondary": "#fdf7ff",
              "surface-bright": "#fdf7fe",
              "primary-dim": "#594b7c",
              "on-tertiary-container": "#5f3956",
              "surface-container-low": "#f8f1fa",
              "inverse-primary": "#d4c3fd",
              "surface-container-high": "#ece6f0",
              "tertiary-container": "#f4bfe3",
              "tertiary-fixed-dim": "#e5b2d5",
              "surface-tint": "#655789",
              "on-error-container": "#6e0523",
              "error": "#a8364b",
              "outline-variant": "#b5b0bb",
              "primary": "#655789",
              "on-tertiary": "#fff7f9",
              "on-tertiary-fixed-variant": "#694260",
              "inverse-surface": "#0f0d12",
              "surface-dim": "#ded8e4",
              "on-primary-fixed": "#352857",
              "secondary": "#625c71",
              "surface-variant": "#e7e0ec",
              "error-dim": "#6b0221",
              "secondary-fixed": "#e8def8",
              "on-primary-container": "#493c6c",
               // Legacy aliases
              success: "#1D9E75",
              warning: "#EF9F27",
              danger: "#E24B4A",
              info: "#378ADD",
              card: "#FFFFFF",
              textPrimary: "#34313a",
              textSecondary: "#615d68",
              border: "#e7e0ec",
      },
      "borderRadius": {
              "DEFAULT": "1rem",
              "lg": "2rem",
              "xl": "3rem",
              "full": "9999px"
      },
      "fontFamily": {
              "headline": ["Manrope", "sans-serif"],
              "body": ["Inter", "sans-serif"],
              "label": ["Inter", "sans-serif"],
              "sans": ["Inter", "system-ui", "sans-serif"]
      }
    },
  },
  plugins: [],
}
