/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "error-container": "#f97386",
        "on-primary-fixed": "#352857",
        "on-tertiary-fixed": "#4a2642",
        "surface-container-low": "#f8f1fa",
        "on-tertiary-container": "#5f3956",
        "primary-container": "#d4c3fd",
        "on-secondary-fixed-variant": "#5f586e",
        "surface-bright": "#fdf7fe",
        "background": "#fdf7fe",
        "tertiary-container": "#f4bfe3",
        "primary-fixed": "#d4c3fd",
        "on-surface-variant": "#615d68",
        "primary-fixed-dim": "#c6b6ee",
        "primary": "#655789",
        "outline": "#7d7983",
        "tertiary-fixed-dim": "#e5b2d5",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#6e0523",
        "inverse-primary": "#d4c3fd",
        "on-primary": "#fdf7ff",
        "secondary": "#625c71",
        "on-tertiary-fixed-variant": "#694260",
        "secondary-fixed-dim": "#dad0ea",
        "surface": "#fdf7fe",
        "on-secondary-container": "#554f63",
        "on-secondary": "#fdf7ff",
        "on-primary-container": "#493c6c",
        "secondary-dim": "#565065",
        "error": "#a8364b",
        "surface-tint": "#655789",
        "surface-container-high": "#ece6f0",
        "error-dim": "#6b0221",
        "surface-dim": "#ded8e4",
        "surface-container-highest": "#e7e0ec",
        "inverse-surface": "#0f0d12",
        "surface-variant": "#e7e0ec",
        "on-surface": "#34313a",
        "secondary-fixed": "#e8def8",
        "on-background": "#34313a",
        "surface-container": "#f2ecf5",
        "on-error": "#fff7f7",
        "outline-variant": "#b5b0bb",
        "primary-dim": "#594b7c",
        "on-primary-fixed-variant": "#524576",
        "tertiary": "#7b5270",
        "on-tertiary": "#fff7f9",
        "secondary-container": "#e8def8",
        "inverse-on-surface": "#a09ba1",
        "tertiary-dim": "#6e4664",
        "tertiary-fixed": "#f4bfe3",
        "on-secondary-fixed": "#423c50",
         // Keeping aliases from legacy components to prevent crash in other views
        success: "#1D9E75",
        warning: "#EF9F27",
        danger: "#E24B4A",
        info: "#378ADD",
        card: "#FFFFFF",
        textPrimary: "#34313a",
        textSecondary: "#615d68",
        border: "#e7e0ec",
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "sans": ['Inter', 'system-ui', 'sans-serif'],
      }
    },
  },
  plugins: [],
}
